classifiers:
  growth:
    checks:
      - popularity
      - maintenance
      - maturity
    syntetics:
      download_divergence: 5
      stale_branches_count: 15
      pr_active_percent: 90
      pr_closed_percent: 90
      issues_active_percent: 90
      issues_closed_percent: 90
    reversed:
      - stale_branches_count
      - issues_active_percent
      - pr_active_percent
      - issues_actual_count
      - pr_actual_count
      - issues_processed_in_avg
      - pr_processed_in_avg
    metrics:
      popularity:
        last_year:
          users_creating_issues_count: 1
          users_commenting_issues_count: 1
          users_creating_pr_count: 1
          users_commenting_pr_count: 1
          stargazers_count: 1
          forks_count: 1
          users_involved_count: 1
          users_involved_no_stars_count: 1
          delta_downloads: 1
        total:
          users_creating_issues_count: 1
          users_commenting_issues_count: 1
          users_creating_pr_count: 1
          users_commenting_pr_count: 1
          watchers_count: 1
          forks_count: 1
          users_involved_no_stars_count: 1
          total_downloads: 1
      maintenance:
        last_year:
          issues_processed_in_avg: 0.5
          issues_closed_percent: 0.5
          issues_all_count: 0.5
          pr_processed_in_avg: 0.5
          pr_closed_percent: 0.5
          pr_all_count: 0.5
          releases_count: 1
          commits: 1
        total:
          issues_closed_percent: 0.5
          issues_non_owner_percent: 0.5
          issues_with_contrib_comments_percent: 0.5
          issues_all_count: 0.5
          issues_processed_in_avg: 0.5
          pr_closed_percent: 0.5
          pr_non_owner_percent: 0.5
          pr_with_contrib_comments_percent: 0.5
          pr_all_count: 0.5
          pr_processed_in_avg: 0.5
          last_year_commits: 1
          releases_count: 1
          stale_branches_count: 1
          life_period: 1
          last_changed: 1
      maturity:
        last_year:
          users_creating_issues_count: 1
          users_commenting_issues_count: 1
          users_creating_pr_count: 1
          users_commenting_pr_count: 1
          stargazers_count: 1
          forks_count: 1
          users_involved_count: 1
          users_involved_no_stars_count: 1
          delta_downloads: 1
          issues_processed_in_avg: 0.5
          issues_closed_percent: 0.5
          issues_all_count: 0.5
          pr_processed_in_avg: 0.5
          pr_closed_percent: 0.5
          pr_all_count: 0.5
          releases_count: 1
          commits: 1
        total:
          users_creating_issues_count: 1
          users_commenting_issues_count: 1
          users_creating_pr_count: 1
          users_commenting_pr_count: 1
          watchers_count: 1
          forks_count: 1
          users_involved_no_stars_count: 1
          total_downloads: 1
          issues_closed_percent: 0.5
          issues_non_owner_percent: 0.5
          issues_with_contrib_comments_percent: 0.5
          issues_all_count: 0.5
          issues_processed_in_avg: 0.5
          pr_closed_percent: 0.5
          pr_non_owner_percent: 0.5
          pr_with_contrib_comments_percent: 0.5
          pr_all_count: 0.5
          pr_processed_in_avg: 0.5
          last_year_commits: 1
          releases_count: 1
          stale_branches_count: 1
          life_period: 1
          last_changed: 1
