stats:
  agility:
    total:
      aggregated_metrics:
        - issues_closed_percent
        - issues_non_owner_percent
        - issues_with_contrib_comments_percent
        - issues_processed_in_avg
        - pr_closed_percent
        - pr_non_owner_percent
        - pr_with_contrib_comments_percent
        - pr_processed_in_avg
      metrics:
        - issues_closed_percent
        - issues_non_owner_percent
        - issues_with_contrib_comments_percent
        - issues_all_count
        - issues_processed_in_avg
        - pr_closed_percent
        - pr_non_owner_percent
        - pr_with_contrib_comments_percent
        - pr_all_count
        - pr_processed_in_avg
        - first_pr_date_int
        - last_pr_date_int
        - first_issue_date_int
        - last_issue_date_int
        - last_release_date_int
        - releases_count
        - commits_count_since_last_release_count
        - stale_branches_count
        - life_period
        - last_changed
      attributes:
        dependencies: Array
        issues_open: Array
        issues_closed: Array
        issues_owner: Array
        issues_non_owner: Array
        issues_with_contrib_comments: Array
        issues_total: Array
        issues_processed_in_avg: Array
        pr_open: Array
        pr_merged: Array
        pr_closed: Array
        pr_owner: Array
        pr_non_owner: Array
        pr_with_contrib_comments: Array
        pr_total: Array
        pr_processed_in_avg: Array
        releases_total_gh: Array
        releases_total_rg: Array
        stale_branches: Array
        branches: Array
        first_pr_date:
        last_pr_date:
        first_issue_date:
        last_issue_date:
        last_release_date:
        commits_count_since_last_release:
        last_year_commits:
    quarter:
      aggregated_metrics:
        - issues_closed_percent
        - issues_processed_in_avg
        - pr_closed_percent
        - pr_processed_in_avg
      metrics:
        - issues_processed_in_avg
        - issues_closed_percent
        - issues_actual_count
        - issues_all_count
        - pr_processed_in_avg
        - pr_closed_percent
        - pr_actual_count
        - pr_all_count
        - releases_count
        - commits
      attributes:
        issues_open: Array
        issues_closed: Array
        issues_total: Array
        issues_actual: Array
        pr_open: Array
        pr_merged: Array
        pr_closed: Array
        pr_total: Array
        pr_actual: Array
        branches: Array
        releases: Array
        releases_total_gh: Array
        releases_total_rg: Array
        commits:
        issues_processed_in_days:
        pr_processed_in_days:
  community:
    total:
      aggregated_metrics: []
      metrics:
        - dependants_count
        - users_creating_issues_count
        - users_commenting_issues_count
        - users_creating_pr_count
        - users_commenting_pr_count
        - watchers_count
        - stargazers_count
        - forks_count
        - users_involved_count
        - users_involved_no_stars_count
        - total_downloads
      attributes:
        dependants: Array
        users_creating_issues: Array
        users_commenting_issues: Array
        users_creating_pr: Array
        users_commenting_pr: Array
        contributors: Array
        watchers: Array
        stargazers: Array
        forks: Array
        users_involved: Array
        owners_github: Array
        owners_rubygems: Array
        total_downloads:
        delta_downloads:
    quarter:
      aggregated_metrics:
        - download_divergence
      metrics:
        - users_creating_issues_count
        - users_commenting_issues_count
        - users_creating_pr_count
        - users_commenting_pr_count
        - stargazers_count
        - forks_count
        - users_involved_count
        - users_involved_no_stars_count
        - download_divergence
        - total_downloads
      attributes:
        users_creating_issues: Array
        users_commenting_issues: Array
        users_creating_pr: Array
        users_commenting_pr: Array
        contributors: Array
        stargazers: Array
        forks: Array
        users_involved: Array
        download_divergence:
        total_downloads:
        delta_downloads:
